name: Testes Cypress

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Instalar dependências
      run: npm install

    - name: Rodar testes Cypress
      run: npm run test:cypress -- --env REPO_URL=https://github.com/gabrielss2406/Cypress_Pipeline

