name: Cypress Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Rodar testes Cypress
      run: npx run test:cypress -- --env REPO_URL=https://github.com/gabrielss2406/Cypress_Pipeline

